services:
  - type: web
    name: plant-disease-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "node server.js"
    runtime: node
    plan: free
    autoDeploy: true
